# -*- coding: utf-8 -*-
"""Statistical_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkF1Z6q6ffugQ5reR4dwljs6PY8Zc6hC
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/df_cleaned.csv')

df.shape

df.head()

df['Status Desc'].value_counts()

df['Date Rptd'] = pd.to_datetime(df['Date Rptd'], format='%Y-%m-%d')
df['DATE OCC'] = pd.to_datetime(df['DATE OCC'], format='%Y-%m-%d')

df['TIME OCC'] = pd.to_datetime(df['TIME OCC'], format='%H:%M:%S').dt.time

df['hour'] = pd.to_datetime(df['TIME OCC'], format='%H:%M:%S').dt.hour
df['day'] = df['DATE OCC'].dt.day_name()
df['month'] = df['DATE OCC'].dt.month
df['year'] = df['DATE OCC'].dt.year

df.info()

"""# **statistical_analysis**

### Descriptive Statistical Analysis (Baseline Understanding)

#### Mean, Median, Mode
"""

# Victim Age
print('Victim Age - Mean:', df['Vict Age'].mean())
print('Victim Age - Median:', df['Vict Age'].median())
print('Victim Age - Mode:', df['Vict Age'].mode()[0])

# Hourly Crime Distribution (using 'hour' column)
# Mean
print('Hourly Crime Distribution - Mean:', df['hour'].mean())
# Median
print('Hourly Crime Distribution - Median:', df['hour'].median())
# Mode
print('Hourly Crime Distribution - Mode:', df['hour'].mode()[0])

"""#### Variance & Standard Deviation"""

# Crime variability over time (e.g., daily crime counts)
daily_crime_counts = df['DATE OCC'].value_counts().sort_index()
print(daily_crime_counts)
print('Daily Crime Counts - Variance:', daily_crime_counts.var())
print('Daily Crime Counts - Standard Deviation:', daily_crime_counts.std())

"""#### Distribution Analysis (Skewness/Kurtosis)"""

# Victim Age
print('Victim Age - Skewness:', df['Vict Age'].skew())
print('Victim Age - Kurtosis:', df['Vict Age'].kurt())

# Hourly crime distribution
print('Hourly Crime Distribution - Skewness:', df['hour'].skew())
print('Hourly Crime Distribution - Kurtosis:', df['hour'].kurt())

# Crime counts (using daily crime counts from previous step)
print('Daily Crime Counts - Skewness:', daily_crime_counts.skew())
print('Daily Crime Counts - Kurtosis:', daily_crime_counts.kurt())

"""### Association & Relationship Analysis

#### Correlation Analysis
"""

print('Correlation between Victim Age and Hour:', df['Vict Age'].corr(df['hour']))

"""#### Cross-tabulation Analysis"""

# Crime Type vs Area
crosstab_crime_area = pd.crosstab(df['Crm Cd Desc'], df['AREA NAME'])
print('Cross-tabulation: Crime Type vs Area\n', crosstab_crime_area.head())

# Crime Type vs Time
crosstab_crime_time = pd.crosstab(df['Crm Cd Desc'], df['hour'])
print('\nCross-tabulation: Crime Type vs Hour\n', crosstab_crime_time.head())

"""### Hypothesis Testing (Statistical Significance)

#### Chi-Square Test
"""

from scipy.stats import chi2_contingency

# Chi-Square Test for Crime Type vs Area
crosstab_crime_area = pd.crosstab(df['Crm Cd Desc'], df['AREA NAME'])
chi2, p_val, _, _ = chi2_contingency(crosstab_crime_area)
print(f"Chi-Square Test: Crime Type vs Area - Chi2: {chi2:.2f}, P-value: {p_val:.4f}")

# Chi-Square Test for Crime Type vs Time of Day (hour)
crosstab_crime_hour = pd.crosstab(df['Crm Cd Desc'], df['hour'])
chi2, p_val, _, _ = chi2_contingency(crosstab_crime_hour)
print(f"Chi-Square Test: Crime Type vs Hour - Chi2: {chi2:.2f}, P-value: {p_val:.4f}")

"""#### Cramér’s V"""

from scipy.stats import chi2_contingency

def cramers_v(x, y):
    confusion_matrix = pd.crosstab(x, y)
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    phi2 = chi2 / n
    r, k = confusion_matrix.shape
    phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))
    rcorr = r - ((r-1)**2)/(n-1)
    kcorr = k - ((k-1)**2)/(n-1)
    return np.sqrt(phi2corr / min((kcorr-1), (rcorr-1)))

# Cramér's V for Crime Type vs Area
cramers_v_crime_area = cramers_v(df['Crm Cd Desc'], df['AREA NAME'])
print(f"Cramér's V for Crime Type vs Area: {cramers_v_crime_area:.4f}")

# Cramér's V for Crime Type vs Hour
cramers_v_crime_time = cramers_v(df['Crm Cd Desc'], df['hour'])
print(f"Cramér's V for Crime Type vs Hour: {cramers_v_crime_time:.4f}")

"""#### ANOVA"""

from scipy.stats import f_oneway

# ANOVA to compare mean victim age across different crime types
# Due to the large number of crime types, we'll select a few top ones for demonstration
top_crime_types = df['Crm Cd Desc'].value_counts().head(5).index

# Prepare data for ANOVA
data_for_anova = []
for crime_type in top_crime_types:
    data_for_anova.append(df[df['Crm Cd Desc'] == crime_type]['Vict Age'].dropna())

# Perform ANOVA
if len(data_for_anova) > 1:
    f_stat, p_val = f_oneway(*data_for_anova)
    print(f"ANOVA (Top 5 Crime Types vs Victim Age) - F-statistic: {f_stat:.2f}, P-value: {p_val:.4f}")
else:
    print("Not enough groups to perform ANOVA effectively with selected crime types.")

"""#### T-Test"""

from scipy.stats import ttest_ind

# Example: Compare victim age in violent vs non-violent crimes
# (Assuming 'ASSAULT' and 'BATTERY' as violent, others as non-violent for simplicity)

violent_crimes = ['ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT', 'BATTERY - SIMPLE ASSAULT']

victim_age_violent = df[df['Crm Cd Desc'].isin(violent_crimes)]['Vict Age'].dropna()
victim_age_non_violent = df[~df['Crm Cd Desc'].isin(violent_crimes)]['Vict Age'].dropna()

# Perform T-test
if not victim_age_violent.empty and not victim_age_non_violent.empty:
    t_stat, p_val = ttest_ind(victim_age_violent, victim_age_non_violent)
    print(f"T-Test (Victim Age in Violent vs Non-Violent Crimes) - T-statistic: {t_stat:.2f}, P-value: {p_val:.4f}")
else:
    print("Could not perform T-Test: One or both groups (violent/non-violent victim age) are empty.")

"""### Temporal Statistical Analysis

#### Time Series Trend Analysis
"""

# Monthly Crime Trends
monthly_crime_counts = df.groupby(df['DATE OCC'].dt.to_period('M')).size()
monthly_crime_counts.index = monthly_crime_counts.index.to_timestamp()
plt.figure(figsize=(12, 6))
monthly_crime_counts.plot()
plt.title('Monthly Crime Trends')
plt.xlabel('Date')
plt.ylabel('Number of Crimes')
plt.show()

# Yearly Crime Trends
yearly_crime_counts = df.groupby(df['DATE OCC'].dt.to_period('Y')).size()
yearly_crime_counts.index = yearly_crime_counts.index.to_timestamp()
plt.figure(figsize=(12, 6))
yearly_crime_counts.plot()
plt.title('Yearly Crime Trends')
plt.xlabel('Date')
plt.ylabel('Number of Crimes')
plt.show()

"""#### Moving Average Smoothing"""

monthly_crime_counts_resampled = df.set_index('DATE OCC').resample('M').size()

# Apply moving average (e.g., 3-month rolling mean)
moving_avg = monthly_crime_counts_resampled.rolling(window=3).mean()

plt.figure(figsize=(12, 6))
monthly_crime_counts_resampled.plot(label='Original Monthly Counts')
moving_avg.plot(label='3-Month Moving Average', color='red')
plt.title('Monthly Crime Trends with Moving Average Smoothing')
plt.xlabel('Date')
plt.ylabel('Number of Crimes')
plt.legend()
plt.show()

"""#### Seasonal Decomposition"""

from statsmodels.tsa.seasonal import seasonal_decompose

# Ensure the time series has sufficient data points for decomposition
# For monthly data, need at least 2 full cycles (e.g., 24 months for yearly seasonality)

# Re-index monthly_crime_counts_resampled to ensure proper frequency for decomposition
monthly_crime_counts_resampled = df.set_index('DATE OCC').resample('M').size().fillna(0)

# Check for minimum length for decomposition
if len(monthly_crime_counts_resampled) >= 24: # Assuming yearly seasonality (12 data points)
    decomposition = seasonal_decompose(monthly_crime_counts_resampled, model='additive', period=12) # Assuming yearly seasonality

    plt.figure(figsize=(14, 8))
    decomposition.plot()
    plt.suptitle('Seasonal Decomposition of Monthly Crime Counts', y=1.02) # Adjust suptitle position
    plt.tight_layout()
    plt.show()
else:
    print(f"Not enough data points ({len(monthly_crime_counts_resampled)}) for seasonal decomposition. Requires at least 24 data points for yearly seasonality.")

"""### Crime Pattern Analysis

#### Conditional Probability (P(Crime Type | Time / Area))
"""

# P(Crime Type | Time)
# Select a specific hour, e.g., 20 (8 PM)
hour_of_interest = 20
crimes_at_hour = df[df['hour'] == hour_of_interest]

if not crimes_at_hour.empty:
    total_crimes_at_hour = len(crimes_at_hour)
    crime_type_counts_at_hour = crimes_at_hour['Crm Cd Desc'].value_counts()
    conditional_prob_time = crime_type_counts_at_hour / total_crimes_at_hour
    print(f"Top 5 Conditional Probabilities P(Crime Type | Hour = {hour_of_interest}):\n{conditional_prob_time.head()}")
else:
    print(f"No crimes recorded at hour {hour_of_interest}.")

# P(Crime Type | Area)
# Select a specific area, e.g., 'Central'
area_of_interest = 'Central'
crimes_in_area = df[df['AREA NAME'] == area_of_interest]

if not crimes_in_area.empty:
    total_crimes_in_area = len(crimes_in_area)
    crime_type_counts_in_area = crimes_in_area['Crm Cd Desc'].value_counts()
    conditional_prob_area = crime_type_counts_in_area / total_crimes_in_area
    print(f"\nTop 5 Conditional Probabilities P(Crime Type | Area = {area_of_interest}):\n{conditional_prob_area.head()}")
else:
    print(f"No crimes recorded in area {area_of_interest}.")

"""#### Co-occurrence Analysis (Weapon × Crime Type relationships)"""

# Co-occurrence matrix for Weapon Desc and Crm Cd Desc
# Filter out 'UNKNOWN WEAPON/OTHER WEAPON' for more meaningful analysis if it's too dominant
df_filtered = df[df['Weapon Desc'] != 'UNKNOWN WEAPON/OTHER WEAPON'].copy()

if not df_filtered.empty:
    co_occurrence_matrix = pd.crosstab(df_filtered['Weapon Desc'], df_filtered['Crm Cd Desc'])
    print("Co-occurrence Matrix (Weapon Desc vs Crime Type):\n")
    display(co_occurrence_matrix.head())

    # To find strong relationships, we can normalize or look at specific cells
    # For example, what crime types are most associated with a 'KNIFE' weapon?
    if 'KNIFE WITH BLADE 6INCHES OR LESS' in co_occurrence_matrix.index:
        knife_crimes = co_occurrence_matrix.loc['KNIFE WITH BLADE 6INCHES OR LESS'].sort_values(ascending=False)
        print("\nTop 5 Crime Types when 'KNIFE WITH BLADE 6INCHES OR LESS' is used:\n")
        display(knife_crimes.head())
    else:
        print("\n'KNIFE WITH BLADE 6INCHES OR LESS' not found in weapon descriptions.")
else:
    print("No data available after filtering 'UNKNOWN WEAPON/OTHER WEAPON'.")

"""### Predictive Statistical Modeling

#### Logistic Regression (predict probability of violent crime)
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Define violent crimes (using the same definition as in T-test)
violent_crimes = ['ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT', 'BATTERY - SIMPLE ASSAULT']
df['is_violent'] = df['Crm Cd Desc'].isin(violent_crimes).astype(int)

# Select features for the model
# Using 'Vict Age', 'hour', 'LAT', 'LON' as numerical features
# One-hot encode 'Vict Sex' and 'AREA NAME' (simplified for demonstration)
features = ['Vict Age', 'hour', 'LAT', 'LON']

X = df[features]
y = df['is_violent']

# Drop rows with NaN values if any (though earlier cleaning should have handled this)
X = X.dropna()
y = y.loc[X.index] # Ensure y aligns with X after dropping NaNs

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and train the Logistic Regression model
log_reg_model = LogisticRegression(max_iter=1000, solver='liblinear') # Increased max_iter for convergence
log_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_log_reg = log_reg_model.predict(X_test)

# Evaluate the model
print("Logistic Regression Model for Violent Crime Prediction:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_log_reg):.4f}")
print("Classification Report:\n", classification_report(y_test, y_pred_log_reg))

"""### Anomaly & Risk Analysis

#### Z-Score Analysis (detect abnormal spikes in daily crime)
"""

from scipy.stats import zscore

# Calculate Z-scores for daily crime counts
daily_crime_counts = df['DATE OCC'].value_counts().sort_index()
daily_crime_counts_df = daily_crime_counts.reset_index()
daily_crime_counts_df.columns = ['DATE OCC', 'Crime_Count']

daily_crime_counts_df['Z_Score'] = zscore(daily_crime_counts_df['Crime_Count'])

# Define a threshold for anomalies (e.g., Z-score > 3 or < -3)
anomaly_threshold = 3
anomalies_zscore = daily_crime_counts_df[
    (daily_crime_counts_df['Z_Score'] > anomaly_threshold) |
    (daily_crime_counts_df['Z_Score'] < -anomaly_threshold)
]

print("Anomalies detected using Z-Score (Daily Crime Counts):")
print(f"Threshold: |Z-Score| > {anomaly_threshold}")
if not anomalies_zscore.empty:
    print(anomalies_zscore)
else:
    print("No significant anomalies detected.")

# Plotting Z-scores over time
plt.figure(figsize=(14, 7))
plt.plot(daily_crime_counts_df['DATE OCC'], daily_crime_counts_df['Crime_Count'], label='Daily Crime Count')
plt.scatter(anomalies_zscore['DATE OCC'], anomalies_zscore['Crime_Count'], color='red', s=50, label='Z-Score Anomaly')
plt.title('Daily Crime Counts with Z-Score Anomalies')
plt.xlabel('Date')
plt.ylabel('Crime Count')
plt.legend()
plt.grid(True)
plt.show()

"""#### IQR Method (outliers in victim age or time distribution)"""

# Outliers in Victim Age using IQR Method
Q1_age = df['Vict Age'].quantile(0.25)
Q3_age = df['Vict Age'].quantile(0.75)
IQR_age = Q3_age - Q1_age

lower_bound_age = Q1_age - 1.5 * IQR_age
upper_bound_age = Q3_age + 1.5 * IQR_age

outliers_age = df[(df['Vict Age'] < lower_bound_age) | (df['Vict Age'] > upper_bound_age)]

print("Outliers in Victim Age using IQR Method:")
print(f"Lower Bound: {lower_bound_age:.2f}, Upper Bound: {upper_bound_age:.2f}")
if not outliers_age.empty:
    print(f"Number of Victim Age Outliers: {len(outliers_age)}")
    print(outliers_age[['Vict Age']].head())
else:
    print("No significant outliers in Victim Age detected.")

# Outliers in Hourly Crime Distribution using IQR Method (example)
Q1_hour = df['hour'].quantile(0.25)
Q3_hour = df['hour'].quantile(0.75)
IQR_hour = Q3_hour - Q1_hour

lower_bound_hour = Q1_hour - 1.5 * IQR_hour
upper_bound_hour = Q3_hour + 1.5 * IQR_hour

outliers_hour = df[(df['hour'] < lower_bound_hour) | (df['hour'] > upper_bound_hour)]

print("\nOutliers in Hourly Crime Distribution using IQR Method:")
print(f"Lower Bound: {lower_bound_hour:.2f}, Upper Bound: {upper_bound_hour:.2f}")
if not outliers_hour.empty:
    print(f"Number of Hourly Crime Outliers: {len(outliers_hour)}")
    print(outliers_hour[['hour']].head())
else:
    print("No significant outliers in Hourly Crime Distribution detected.")

"""#### Classification Models (Random Forest / Decision Trees for crime type prediction)"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# For simplicity, let's predict the top 5 crime types
top_5_crime_types = df['Crm Cd Desc'].value_counts().head(5).index.tolist()
df_filtered_crimes = df[df['Crm Cd Desc'].isin(top_5_crime_types)].copy()

# Encode the target variable 'Crm Cd Desc'
le = LabelEncoder()
df_filtered_crimes['Crm_Type_Encoded'] = le.fit_transform(df_filtered_crimes['Crm Cd Desc'])

# Select features (using numerical features. For a more robust model, include one-hot encoded categorical features)
features_clf = ['Vict Age', 'hour', 'LAT', 'LON']
X_clf = df_filtered_crimes[features_clf]
y_clf = df_filtered_crimes['Crm_Type_Encoded']

# Handle potential NaNs
X_clf = X_clf.dropna()
y_clf = y_clf.loc[X_clf.index]

# Split data
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_clf, y_clf, test_size=0.3, random_state=42)

# Initialize and train a Random Forest Classifier model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1) # n_jobs=-1 uses all available cores
rf_model.fit(X_train_clf, y_train_clf)

# Make predictions
y_pred_rf = rf_model.predict(X_test_clf)

# Evaluate the model
print("Random Forest Classifier for Crime Type Prediction:")
print(f"Accuracy: {accuracy_score(y_test_clf, y_pred_rf):.4f}")
print("Classification Report:\n", classification_report(y_test_clf, y_pred_rf, target_names=le.classes_))

"""#### Linear Regression (predict crime count trends)"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Prepare data for Linear Regression (e.g., predicting daily crime counts over time)
# We'll use the 'daily_crime_counts' Series from earlier

time_series_df = pd.DataFrame({
    'Date': daily_crime_counts.index,
    'Crime_Count': daily_crime_counts.values
})

time_series_df['Ordinal_Date'] = time_series_df['Date'].apply(lambda x: x.toordinal())

X_lin = time_series_df[['Ordinal_Date']]
y_lin = time_series_df['Crime_Count']

# Split data into training and testing sets
X_train_lin, X_test_lin, y_train_lin, y_test_lin = train_test_split(X_lin, y_lin, test_size=0.3, random_state=42)

# Initialize and train the Linear Regression model
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train_lin, y_train_lin)

# Make predictions
y_pred_lin_reg = lin_reg_model.predict(X_test_lin)

# Evaluate the model
print("Linear Regression Model for Crime Count Trends:")
print(f"Mean Squared Error: {mean_squared_error(y_test_lin, y_pred_lin_reg):.2f}")
print(f"R-squared: {r2_score(y_test_lin, y_pred_lin_reg):.4f}")

# Plotting the trend
plt.figure(figsize=(12, 6))
plt.plot(time_series_df['Date'], time_series_df['Crime_Count'], label='Actual Daily Crime Counts')
plt.plot(X_test_lin['Ordinal_Date'], y_pred_lin_reg, color='red', label='Predicted Trend (Test Set)')
plt.title('Linear Regression Trend of Daily Crime Counts')
plt.xlabel('Date')
plt.ylabel('Crime Count')
plt.legend()
plt.show()

"""### Predictive Statistical Modeling

#### Logistic Regression (predict probability of violent crime)
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Define violent crimes (using the same definition as in T-test)
violent_crimes = ['ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT', 'BATTERY - SIMPLE ASSAULT']
df['is_violent'] = df['Crm Cd Desc'].isin(violent_crimes).astype(int)

# Select features for the model
# Using 'Vict Age', 'hour', 'LAT', 'LON' as numerical features
# One-hot encode 'Vict Sex' and 'AREA NAME' (simplified for demonstration)
features = ['Vict Age', 'hour', 'LAT', 'LON']

X = df[features]
y = df['is_violent']

# Drop rows with NaN values if any (though earlier cleaning should have handled this)
X = X.dropna()
y = y.loc[X.index] # Ensure y aligns with X after dropping NaNs

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and train the Logistic Regression model
log_reg_model = LogisticRegression(max_iter=1000, solver='liblinear') # Increased max_iter for convergence
log_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_log_reg = log_reg_model.predict(X_test)

# Evaluate the model
print("Logistic Regression Model for Violent Crime Prediction:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_log_reg):.4f}")
print("Classification Report:\n", classification_report(y_test, y_pred_log_reg))

"""#### Classification Models (Random Forest / Decision Trees for crime type prediction)"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

# For simplicity, let's predict the top 5 crime types
top_5_crime_types = df['Crm Cd Desc'].value_counts().head(5).index.tolist()
df_filtered_crimes = df[df['Crm Cd Desc'].isin(top_5_crime_types)].copy()

# Encode the target variable 'Crm Cd Desc'
le = LabelEncoder()
df_filtered_crimes['Crm_Type_Encoded'] = le.fit_transform(df_filtered_crimes['Crm Cd Desc'])

# Select features (using numerical and some encoded categorical features)
features_clf = ['Vict Age', 'hour', 'LAT', 'LON']
X_clf = df_filtered_crimes[features_clf]
y_clf = df_filtered_crimes['Crm_Type_Encoded']

# Handle potential NaNs
X_clf = X_clf.dropna()
y_clf = y_clf.loc[X_clf.index]

# Split data
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_clf, y_clf, test_size=0.3, random_state=42)

# Initialize and train a Random Forest Classifier model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1) # n_jobs=-1 uses all available cores
rf_model.fit(X_train_clf, y_train_clf)

# Make predictions
y_pred_rf = rf_model.predict(X_test_clf)

# Evaluate the model
print("Random Forest Classifier for Crime Type Prediction:")
print(f"Accuracy: {accuracy_score(y_test_clf, y_pred_rf):.4f}")
print("Classification Report:\n", classification_report(y_test_clf, y_pred_rf, target_names=le.classes_))

"""### Anomaly & Risk Analysis

#### IQR Method (outliers in victim age or time distribution)
"""

# Outliers in Victim Age using IQR Method
Q1_age = df['Vict Age'].quantile(0.25)
Q3_age = df['Vict Age'].quantile(0.75)
IQR_age = Q3_age - Q1_age

lower_bound_age = Q1_age - 1.5 * IQR_age
upper_bound_age = Q3_age + 1.5 * IQR_age

outliers_age = df[(df['Vict Age'] < lower_bound_age) | (df['Vict Age'] > upper_bound_age)]

print("Outliers in Victim Age using IQR Method:")
print(f"Lower Bound: {lower_bound_age:.2f}, Upper Bound: {upper_bound_age:.2f}")
if not outliers_age.empty:
    print(f"Number of Victim Age Outliers: {len(outliers_age)}")
    print(outliers_age[['Vict Age']].head())
else:
    print("No significant outliers in Victim Age detected.")

# Outliers in Hourly Crime Distribution using IQR Method (example)
Q1_hour = df['hour'].quantile(0.25)
Q3_hour = df['hour'].quantile(0.75)
IQR_hour = Q3_hour - Q1_hour

lower_bound_hour = Q1_hour - 1.5 * IQR_hour
upper_bound_hour = Q3_hour + 1.5 * IQR_hour

outliers_hour = df[(df['hour'] < lower_bound_hour) | (df['hour'] > upper_bound_hour)]

print("\nOutliers in Hourly Crime Distribution using IQR Method:")
print(f"Lower Bound: {lower_bound_hour:.2f}, Upper Bound: {upper_bound_hour:.2f}")
if not outliers_hour.empty:
    print(f"Number of Hourly Crime Outliers: {len(outliers_hour)}")
    print(outliers_hour[['hour']].head())
else:
    print("No significant outliers in Hourly Crime Distribution detected.")